### ISSUE TITLE
Target .NET Standard 2.0 instead or in addition to 1.0?

### ISSUE THREAD

**Issue by divega** [damieng/Linq.Translations#11]
@davidfowl, @damieng I was wondering if the package should target 2.0 instead of 1.0 as the project currently does. I know some reasons we usually recommend 2.0, but because this one doesn’t have any dependencies, I am not sure the same reasons apply.

**Comment by davidfowl** [comment]
Yes it should 😬

**Comment by damieng** [comment]
So switch it to 2.0 instead of or in addition to?

**Comment by davidfowl** [comment]
Switch to 2.0 drop 1.0
